# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Doe
email: johndoe@email.com
description: >
  This template is available for customization at:
    <a href="https://github.com/austin94/resume-builder">
    https://github.com/austin94/resume-builder</a>
baseurl: ""
url:
github_username:  johndoe
markdown: kramdown
